Venkat's comments

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -22,8 +22,8 @@ FROM debian:jessie
 
 # Specify the cadence version to be built into this docker image
 # See https://github.com/uber/cadence/tags
-ARG build_branch
-RUN if [ -z "$build_branch" ]; then echo "build_branch NOT SET - ERROR"; exit 1; else : ; fi
+ARG git_branch
+RUN if [ -z "$git_branch" ]; then echo "ERROR: git_branch NOT SET. Usage: docker build . --build-arg git_branch=YOUR_CHECKOUT_BRANCH"; exit 1; else : ; fi
 
 # get golang 1.8.1
 RUN apt-get update && apt-get install -y --no-install-recommends \
@@ -65,7 +65,7 @@ RUN go get -u github.com/Masterminds/glide
 RUN go get -u github.com/golang/lint/golint
 
 RUN git clone --depth=50 https://github.com/uber/cadence.git $CADENCE_HOME
-RUN cd $CADENCE_HOME; git checkout $build_branch; make bins_nothrift
+RUN cd $CADENCE_HOME; git checkout $git_branch; make bins_nothrift
 
 EXPOSE 7933 7934 7935
 
